name: Update Metrics

on:
  schedule:
    - cron: "30 0 * * *" # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: gns-x
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          filename: metrics.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage, bytes-size
          plugin_languages_threshold: 2%
          plugin_languages_limit: 10
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_lines: yes

